// <auto-generated />
using Lab1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250930065018_AddSeedsData")]
    partial class AddSeedsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab1.Models.AccountMember", b =>
                {
                    b.Property<string>("MemberID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberRole")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.ToTable("AccountMembers");

                    b.HasData(
                        new
                        {
                            MemberID = "admin",
                            EmailAddress = "admin@example.com",
                            FullName = "Administrator",
                            MemberPassword = "admin123",
                            MemberRole = 1
                        },
                        new
                        {
                            MemberID = "user1",
                            EmailAddress = "user1@example.com",
                            FullName = "User One",
                            MemberPassword = "user123",
                            MemberRole = 0
                        });
                });

            modelBuilder.Entity("Lab1.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Mobile"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Laptop"
                        });
                });

            modelBuilder.Entity("Lab1.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            ProductName = "Iphone 17 Pro Max",
                            UnitPrice = 599m,
                            UnitsInStock = 100
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            ProductName = "Iphone 17 Pro",
                            UnitPrice = 499m,
                            UnitsInStock = 150
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            ProductName = "Iphone 17 Air",
                            UnitPrice = 399m,
                            UnitsInStock = 200
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 2,
                            ProductName = "Macbook Air M4",
                            UnitPrice = 1299m,
                            UnitsInStock = 200
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 2,
                            ProductName = "Macbook Pro M4",
                            UnitPrice = 1599m,
                            UnitsInStock = 200
                        });
                });

            modelBuilder.Entity("Lab1.Models.Product", b =>
                {
                    b.HasOne("Lab1.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lab1.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
